name: build-stg

on:
  workflow_dispatch:
  push:
    branches:
      - "*stg*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Setup
        run: "sudo docker run --privileged --rm tonistiigi/binfmt --install arm64,riscv64,arm"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jtoper/fantasty-finance:stg-latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

